### ISSUE TITLE
error in 2015b('MaxFunctionEvaluations' is not an option for FMINCON.)

### ISSUE THREAD

**Issue by Jiongyu** [danielrherber/optimal-control-direct-method-examples#3]
>> INSTALL_Direct_Method_Examples
--- Adding submission contents to path
 
--- Obtaining required web zips
Already available MFX 51104
Already available MFX 65434
 
--- Adding submission contents to path
 
--- Closing BrysonHo166
 
--- Adding submission contents to path
 
--- Opening Run_All_Examples
 
--- Closing INSTALL_Direct_Method_Examples
 
>> Run_All_Examples
error optimoptions (line 105)
'MaxFunctionEvaluations' is not an option for FMINCON.
A list of options can be found on the FMINCON documentation page.

error Method_SingleShooting (line 24)
    options = optimoptions(@fmincon,'display','iter','MaxFunctionEvaluations',1e5); % option

error Run_All_Examples (line 13)
Method_SingleShooting

**Comment by danielrherber** [comment]
Does changing 'MaxFunctionEvaluations' to "MaxFunEvals' fix the issue when running on 2015b? Do you run into any other issues when using this version? Unfortunately, I don't have this older version of MATLAB installed but I want to try to have this repository support old versions.

**Comment by Jiongyu** [comment]
it`s work in 2015b, thank you.

**Comment by danielrherber** [comment]
Issue should be fixed in commit 1d996c95605275798982591d47c6bd1578019081.
